apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sql-demo
  namespace: spark-apps
spec:
  type: Scala
  mode: cluster
  image: "spark-sql-demo:latest"
  imagePullPolicy: Never
  mainClass: com.wsy.demo.sql.Main
  mainApplicationFile: "local:///opt/lib/spark-sql-demo.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: "logs"
      hostPath:
        path: "/Users/wangsenyuan/git/github/spark-sql-demo/spark-logs"
        type: Directory
  sparkConf:
    spark.eventLog.enabled: "true"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "logs"
        mountPath: "/tmp/spark-events"
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "logs"
        mountPath: "/app/logs"
