---
kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-greenplum-pod-templates
  namespace: default
data:
  driver: |-
    apiVersion: v1
    kind: Pod
    spec:
      volumes:
      - name: source-data-volume
        emptyDir: {}
      - name: metrics-files-volume
        emptyDir: {}
      containers:
      - name: spark-greenplum-demo-driver
        env:
        - name: CHECKPOINT_DIR
          value: "hdfs://192.168.95.152:9000/user/spark/checkpoints/"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  executor: |-
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: spark-greenplum-demo-executor
        env:
        - name: CHECKPOINT_DIR
          value: "hdfs://192.168.95.152:9000/user/spark/checkpoints/"
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  spark-log4j: |-
    rootLogger.level = info
    rootLogger.appenderRef.stdout.ref = console
    appender.console.type = Console
    appender.console.name = console
    appender.console.target = SYSTEM_ERR
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex

---
apiVersion: batch/v1
kind: Job
metadata:
  name: spark-greenplum-job
  namespace: default
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: spark
          image: registry.cn-hangzhou.aliyuncs.com/fesco/spark:v3.4.0
          imagePullPolicy: IfNotPresent
          args: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://https://kubernetes.default.svc.cluster.local:443 \
            --deploy-mode cluster \
            --name spark-greenplum-demo \
            --class com.wsy.demo.greenplum.Main \
            --conf spark.kubernetes.authenticate.driver.serviceAccountName=sparkx \
            --conf spark.jars.ivy=/tmp/.ivy \
            --conf spark.dynamicAllocation.enabled=true \
            --conf spark.dynamicAllocation.shuffleTracking.enabled=true \
            --conf spark.dynamicAllocation.shuffleTracking.timeout=600 \
            --conf spark.dynamicAllocation.minExecutors=4 \
            --conf spark.dynamicAllocation.maxExecutors=4 \
            --conf spark.kubernetes.allocation.batch.size=10 \
            --conf spark.dynamicAllocation.executorAllocationRatio=1 \
            --conf spark.dynamicAllocation.schedulerBacklogTimeout=1 \
            --conf spark.driver.memory=1G \
            --conf spark.executor.memory=1G \
            --conf spark.executor.cores=2 \
            --conf spark.sql.shuffle.partitions=10 \
            --conf spark.kubernetes.container.image=registry.cn-hangzhou.aliyuncs.com/fesco/spark-sql-demo:1.8 \
            --conf spark.kubernetes.container.image.pullPolicy=Always \
            --conf spark.kubernetes.namespace=default \
            --conf spark.kubernetes.executor.deleteOnTermination=false \
            --conf spark.kubernetes.driver.podTemplateFile='/opt/spark/conf/driver_pod_template.yml' \
            --conf spark.kubernetes.executor.podTemplateFile='/opt/spark/conf/executor_pod_template.yml' \
            local:///opt/lib/spark-sql-demo.jar "
          ]
          volumeMounts:
            - name: spark-pod-template
              mountPath: /opt/spark/conf/driver_pod_template.yml
              subPath: driver
            - name: spark-pod-template
              mountPath: /opt/spark/conf/executor_pod_template.yml
              subPath: executor
            - name: spark-pod-template
              mountPath: /opt/spark/conf/log4j2.properties
              subPath: spark-log4j
      serviceAccountName: sparkx
      restartPolicy: Never
      volumes:
        - name: spark-pod-template
          configMap:
            name: spark-greenplum-pod-templates
            defaultMode: 420
  backoffLimit: 4
