apiVersion: v1
kind: PersistentVolume
metadata:
  name: history-server-logs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: spark-logs
  nfs:
    path: /maycur/spark_logs/
    server: 192.168.95.187
    readOnly: false


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: history-server-logs-pvc
  namespace: spark-apps
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: spark-logs

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: registry.cn-hangzhou.aliyuncs.com/fesco/spark-history-server:v3.4.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          command:
            - '/opt/spark/sbin/start-history-server.sh'
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "false"
            - name: SPARK_HISTORY_OPTS
              value: "-Dspark.history.fs.logDirectory=/tmp/spark-events -Dspark.history.fs.cleaner.enabled=false"
            - name: SPARK_CONF_DIR
              value: /opt/spark/conf
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080
          volumeMounts:
            - name: data
              mountPath: /tmp/spark-events
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: history-server-logs-pvc
            readOnly: false

---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: spark-apps
spec:
  selector:
    app: spark-history-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
