apiVersion: v1
kind: PersistentVolume
metadata:
  name: history-server-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: "/Users/wangsenyuan/git/github/spark-sql-demo/spark-logs"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: history-server-logs-pvc
  namespace: spark-apps
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  namespace: spark-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      name: spark-history-server
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: spark-history-server:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          command:
            - '/opt/spark/sbin/start-history-server.sh'
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "false"
            - name: SPARK_HISTORY_OPTS
              value: "-Dspark.history.fs.logDirectory=/tmp/spark-events"
            - name: SPARK_CONF_DIR
              value: /opt/spark/conf
          ports:
            - name: http
              protocol: TCP
              containerPort: 18080
          volumeMounts:
            - name: data
              mountPath: /tmp/spark-events
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: history-server-logs-pvc
            readOnly: true

---
