#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-sql-demo
  namespace: spark-apps
spec:
  type: Scala
  mode: cluster
  image: "spark-sql-demo:latest"
  imagePullPolicy: Never
  mainClass: com.wsy.demo.streaming.Main
  mainApplicationFile: "local:///opt/lib/spark-sql-demo.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
    - name: "logs"
      hostPath:
        path: "/Users/wangsenyuan/git/github/spark-sql-demo/spark-logs"
        type: Directory
  sparkConf:
    spark.eventLog.enabled: "true"
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "logs"
        mountPath: "/tmp/spark-events"
  executor:
    cores: 1
    instances: 3
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
      - name: "logs"
        mountPath: "/app/logs"
